spring.application.name=openchat
spring.security.oauth2.client.registration.google.client-id=777520761231-esllclesfarec9lp95v5skr79fmjhea7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# ===============================
# Datasource (H2 - In Memory)
# ===============================
spring.datasource.url=jdbc:h2:mem:openchat
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.profiles.active=redis